USE [Data_Governance]
GO

-- insert seed records
-- thanks http://random-name-generator.info/index.php?n=100&g=1&st=3
insert into dbo.[User] (Username, FullName, FirstName, LastName, Department, Title, Email) values
	('Hertha-Barham','Hertha Barham','Hertha','Barham','Accident and Emergency','Boss','hBarham@my_hosptital.rocks'),
('Amada-Tisdale','Amada Tisdale','Amada','Tisdale','Accident and Emergency','Worker','aTisdale@my_hosptital.rocks'),
('Bryce-Bayne','Bryce Bayne','Bryce','Bayne','Accident and Emergency','Manager','bBayne@my_hosptital.rocks'),
('Hae-Weiner','Hae Weiner','Hae','Weiner','Accident and Emergency','Mr Cool','hWeiner@my_hosptital.rocks'),
('Shonda-Purcell','Shonda Purcell','Shonda','Purcell','Accident and Emergency','Do it right','sPurcell@my_hosptital.rocks'),
('Earle-Archuleta','Earle Archuleta','Earle','Archuleta','Accident and Emergency','First at Work','eArchuleta@my_hosptital.rocks'),
('Garth-Cornwell','Garth Cornwell','Garth','Cornwell','Accident and Emergency','Worker','gCornwell@my_hosptital.rocks'),
('Mardell-Crews','Mardell Crews','Mardell','Crews','Accident and Emergency','Worker','mCrews@my_hosptital.rocks'),
('Jade-Wiggins','Jade Wiggins','Jade','Wiggins','Accident and Emergency','Worker','jWiggins@my_hosptital.rocks'),
('Marylee-Rauch','Marylee Rauch','Marylee','Rauch','Accident and Emergency','Worker','mRauch@my_hosptital.rocks'),
('Magda-Shook','Magda Shook','Magda','Shook','Accident and Emergency','Worker','mShook@my_hosptital.rocks'),
('Nannie-Redmond','Nannie Redmond','Nannie','Redmond','Accident and Emergency','Boss','nRedmond@my_hosptital.rocks'),
('Candance-Singer','Candance Singer','Candance','Singer','Accident and Emergency','Worker','cSinger@my_hosptital.rocks'),
('Renata-Bigelow','Renata Bigelow','Renata','Bigelow','Accident and Emergency','Manager','rBigelow@my_hosptital.rocks'),
('Eve-Wilkinson','Eve Wilkinson','Eve','Wilkinson','Accident and Emergency','Mr Cool','eWilkinson@my_hosptital.rocks'),
('Tiesha-Chavis','Tiesha Chavis','Tiesha','Chavis','Admissions','Do it right','tChavis@my_hosptital.rocks'),
('Bernardine-Scherer','Bernardine Scherer','Bernardine','Scherer','Admissions','First at Work','bScherer@my_hosptital.rocks'),
('Stefania-Wakefield','Stefania Wakefield','Stefania','Wakefield','Admissions','Worker','sWakefield@my_hosptital.rocks'),
('Roselia-Hoskins','Roselia Hoskins','Roselia','Hoskins','Admissions','Worker','rHoskins@my_hosptital.rocks'),
('Hyun-Rockwell','Hyun Rockwell','Hyun','Rockwell','Admissions','Worker','hRockwell@my_hosptital.rocks'),
('Marcelina-Brinson','Marcelina Brinson','Marcelina','Brinson','Admissions','Worker','mBrinson@my_hosptital.rocks'),
('Grazyna-Peter','Grazyna Peter','Grazyna','Peter','Admissions','Worker','gPeter@my_hosptital.rocks'),
('Yuko-Manley','Yuko Manley','Yuko','Manley','Admissions','Boss','yManley@my_hosptital.rocks'),
('Lizzie-Olivas','Lizzie Olivas','Lizzie','Olivas','Admissions','Worker','lOlivas@my_hosptital.rocks'),
('Barbar-Durand','Barbar Durand','Barbar','Durand','Admissions','Manager','bDurand@my_hosptital.rocks'),
('Jung-Romano','Jung Romano','Jung','Romano','Admissions','Mr Cool','jRomano@my_hosptital.rocks'),
('Theola-Blanchette','Theola Blanchette','Theola','Blanchette','Cardiology','Do it right','tBlanchette@my_hosptital.rocks'),
('Patrick-Watters','Patrick Watters','Patrick','Watters','Cardiology','First at Work','pWatters@my_hosptital.rocks'),
('Camila-Theriault','Camila Theriault','Camila','Theriault','Cardiology','Worker','cTheriault@my_hosptital.rocks'),
('Golda-Henke','Golda Henke','Golda','Henke','Cardiology','Worker','gHenke@my_hosptital.rocks'),
('Alysia-Casteel','Alysia Casteel','Alysia','Casteel','Cardiology','Worker','aCasteel@my_hosptital.rocks'),
('Livia-Crayton','Livia Crayton','Livia','Crayton','Oncology','Worker','lCrayton@my_hosptital.rocks'),
('Matilde-Alonzo','Matilde Alonzo','Matilde','Alonzo','Oncology','Worker','mAlonzo@my_hosptital.rocks'),
('Cleora-Parnell','Cleora Parnell','Cleora','Parnell','Oncology','Boss','cParnell@my_hosptital.rocks'),
('Willette-Marr','Willette Marr','Willette','Marr','Oncology','Worker','wMarr@my_hosptital.rocks'),
('Eddie-Pereira','Eddie Pereira','Eddie','Pereira','Oncology','Manager','ePereira@my_hosptital.rocks'),
('Evelin-Petersen','Evelin Petersen','Evelin','Petersen','Oncology','Mr Cool','ePetersen@my_hosptital.rocks'),
('Michaela-Mckeown','Michaela Mckeown','Michaela','Mckeown','Oncology','Do it right','mMckeown@my_hosptital.rocks'),
('Reyna-Blum','Reyna Blum','Reyna','Blum','Pharmacy','First at Work','rBlum@my_hosptital.rocks'),
('Gail-Sapp','Gail Sapp','Gail','Sapp','Pharmacy','Worker','gSapp@my_hosptital.rocks'),
('Giselle-Sams','Giselle Sams','Giselle','Sams','Pharmacy','Worker','gSams@my_hosptital.rocks'),
('Rhona-Whiting','Rhona Whiting','Rhona','Whiting','Pharmacy','Worker','rWhiting@my_hosptital.rocks'),
('Merrill-Hirsch','Merrill Hirsch','Merrill','Hirsch','Pharmacy','Worker','mHirsch@my_hosptital.rocks'),
('Vina-Winchester','Vina Winchester','Vina','Winchester','Pharmacy','Worker','vWinchester@my_hosptital.rocks'),
('Ronnie-Nickerson','Ronnie Nickerson','Ronnie','Nickerson','Pharmacy','Boss','rNickerson@my_hosptital.rocks'),
('Corrine-Landry','Corrine Landry','Corrine','Landry','Pharmacy','Worker','cLandry@my_hosptital.rocks'),
('Andrew-Janssen','Andrew Janssen','Andrew','Janssen','Radiotherapy','Manager','aJanssen@my_hosptital.rocks'),
('Fatimah-Sheehan','Fatimah Sheehan','Fatimah','Sheehan','Radiotherapy','Mr Cool','fSheehan@my_hosptital.rocks'),
('Andrea-Rainey','Andrea Rainey','Andrea','Rainey','Radiotherapy','Do it right','aRainey@my_hosptital.rocks'),
('John-Knutson','John Knutson','John','Knutson','Radiotherapy','First at Work','jKnutson@my_hosptital.rocks'),
('Andre-Meredith','Andre Meredith','Andre','Meredith','Radiotherapy','Worker','aMeredith@my_hosptital.rocks'),
('Dalene-Binkley','Dalene Binkley','Dalene','Binkley','Radiotherapy','Worker','dBinkley@my_hosptital.rocks'),
('Shaquana-Neeley','Shaquana Neeley','Shaquana','Neeley','Radiotherapy','Worker','sNeeley@my_hosptital.rocks'),
('Willy-Jarvis','Willy Jarvis','Willy','Jarvis','Radiotherapy','Worker','wJarvis@my_hosptital.rocks'),
('Dirk-Palma','Dirk Palma','Dirk','Palma','Radiotherapy','Worker','dPalma@my_hosptital.rocks'),
('Raphael-Albers','Raphael Albers','Raphael','Albers','Radiotherapy','Boss','rAlbers@my_hosptital.rocks'),
('Kenya-Durham','Kenya Durham','Kenya','Durham','Radiotherapy','Worker','kDurham@my_hosptital.rocks'),
('Nikole-Janes','Nikole Janes','Nikole','Janes','Radiotherapy','Manager','nJanes@my_hosptital.rocks'),
('Nigel-Grove','Nigel Grove','Nigel','Grove','Urology','Mr Cool','nGrove@my_hosptital.rocks'),
('Wynona-Lancaster','Wynona Lancaster','Wynona','Lancaster','Urology','Do it right','wLancaster@my_hosptital.rocks'),
('Delorse-Pence','Delorse Pence','Delorse','Pence','Urology','First at Work','dPence@my_hosptital.rocks'),
('Claudie-Irwin','Claudie Irwin','Claudie','Irwin','Urology','Worker','cIrwin@my_hosptital.rocks'),
('Roxane-Moreau','Roxane Moreau','Roxane','Moreau','Urology','Worker','rMoreau@my_hosptital.rocks'),
('Jae-Clements','Jae Clements','Jae','Clements','Urology','Worker','jClements@my_hosptital.rocks'),
('Milagro-Montalvo','Milagro Montalvo','Milagro','Montalvo','Urology','Worker','mMontalvo@my_hosptital.rocks'),
('Lang-Dowling','Lang Dowling','Lang','Dowling','Urology','Worker','lDowling@my_hosptital.rocks'),
('Myles-Fulton','Myles Fulton','Myles','Fulton','Analytics','Boss','mFulton@my_hosptital.rocks'),
('Otelia-Bernstein','Otelia Bernstein','Otelia','Bernstein','Analytics','Worker','oBernstein@my_hosptital.rocks'),
('Crystle-Homer','Crystle Homer','Crystle','Homer','Analytics','Manager','cHomer@my_hosptital.rocks'),
('Lawana-Herron','Lawana Herron','Lawana','Herron','Analytics','Mr Cool','lHerron@my_hosptital.rocks'),
('Ollie-Pinto','Ollie Pinto','Ollie','Pinto','Analytics','Do it right','oPinto@my_hosptital.rocks'),
('Stefani-Schwab','Stefani Schwab','Stefani','Schwab','Analytics','First at Work','sSchwab@my_hosptital.rocks'),
('Nereida-Minor','Nereida Minor','Nereida','Minor','Analytics','Worker','nMinor@my_hosptital.rocks'),
('Kirby-Strother','Kirby Strother','Kirby','Strother','Analytics','Worker','kStrother@my_hosptital.rocks'),
('Erinn-Spooner','Erinn Spooner','Erinn','Spooner','Analytics','Worker','eSpooner@my_hosptital.rocks'),
('Youlanda-Driver','Youlanda Driver','Youlanda','Driver','Analytics','Worker','yDriver@my_hosptital.rocks'),
('Ashlyn-Schulze','Ashlyn Schulze','Ashlyn','Schulze','Analytics','Worker','aSchulze@my_hosptital.rocks'),
('Brianne-Lemmon','Brianne Lemmon','Brianne','Lemmon','Analytics','Boss','bLemmon@my_hosptital.rocks'),
('Bebe-Ahern','Bebe Ahern','Bebe','Ahern','Analytics','Worker','bAhern@my_hosptital.rocks'),
('Leigh-Bolen','Leigh Bolen','Leigh','Bolen','Ophthalmology','Manager','lBolen@my_hosptital.rocks'),
('Shila-Pryor','Shila Pryor','Shila','Pryor','Ophthalmology','Mr Cool','sPryor@my_hosptital.rocks'),
('Particia-Estrella','Particia Estrella','Particia','Estrella','Ophthalmology','Do it right','pEstrella@my_hosptital.rocks'),
('Cheree-Seifert','Cheree Seifert','Cheree','Seifert','Ophthalmology','First at Work','cSeifert@my_hosptital.rocks'),
('Christi-Lear','Christi Lear','Christi','Lear','Ophthalmology','Worker','cLear@my_hosptital.rocks'),
('Dannie-Kenney','Dannie Kenney','Dannie','Kenney','Ophthalmology','Worker','dKenney@my_hosptital.rocks'),
('Jarod-Tan','Jarod Tan','Jarod','Tan','Ophthalmology','Worker','jTan@my_hosptital.rocks'),
('Alejandra-Bedard','Alejandra Bedard','Alejandra','Bedard','Orthopaedics','Worker','aBedard@my_hosptital.rocks'),
('Jerrie-Joyce','Jerrie Joyce','Jerrie','Joyce','Orthopaedics','Worker','jJoyce@my_hosptital.rocks'),
('Tiny-Rohr','Tiny Rohr','Tiny','Rohr','Orthopaedics','Boss','tRohr@my_hosptital.rocks'),
('Donnetta-Grice','Donnetta Grice','Donnetta','Grice','Orthopaedics','Worker','dGrice@my_hosptital.rocks'),
('Ruthanne-Cranford','Ruthanne Cranford','Ruthanne','Cranford','Orthopaedics','Manager','rCranford@my_hosptital.rocks'),
('Annis-Turk','Annis Turk','Annis','Turk','Orthopaedics','Mr Cool','aTurk@my_hosptital.rocks'),
('Ilona-Lassiter','Ilona Lassiter','Ilona','Lassiter','Orthopaedics','Do it right','iLassiter@my_hosptital.rocks'),
('Daren-Ladd','Daren Ladd','Daren','Ladd','Orthopaedics','First at Work','dLadd@my_hosptital.rocks'),
('Jenae-Woodbury','Jenae Woodbury','Jenae','Woodbury','Orthopaedics','Worker','jWoodbury@my_hosptital.rocks'),
('Ashanti-Pritchett','Ashanti Pritchett','Ashanti','Pritchett','Orthopaedics','Worker','aPritchett@my_hosptital.rocks'),
('Martina-Dawkins','Martina Dawkins','Martina','Dawkins','Orthopaedics','Worker','mDawkins@my_hosptital.rocks'),
('Oma-Esposito','Oma Esposito','Oma','Esposito','Orthopaedics','Worker','oEsposito@my_hosptital.rocks'),
('Carisa-Forbes','Carisa Forbes','Carisa','Forbes','Orthopaedics','Worker','cForbes@my_hosptital.rocks'),
('Marti-Winter','Marti Winter','Marti','Winter','Orthopaedics','Boss','mWinter@my_hosptital.rocks')
GO
insert into [Data_Governance].app.UserRoleLinks (UserId, UserRolesId) values
(1,2),
(2,2),
(3,3),
(4,3),
(5,4),
(6,4),
(7,5),
(8,5),
(9,2),
(10,2),
(11,3),
(12,3),
(13,4),
(14,4),
(15,5),
(16,5),
(17,2),
(18,2),
(19,3),
(20,3),
(21,4),
(22,4),
(23,5),
(24,5),
(25,2),
(26,2),
(27,3),
(28,3),
(29,4),
(30,4),
(31,5),
(32,5),
(33,2),
(34,2),
(35,3),
(36,3),
(37,4),
(38,4),
(39,5),
(40,5),
(41,2),
(42,2),
(43,3),
(44,3),
(45,4),
(46,4),
(47,5),
(48,5),
(49,2),
(50,2),
(51,3),
(52,3),
(53,4),
(54,4),
(55,5),
(56,5),
(57,2),
(58,2),
(59,3),
(60,3),
(61,4),
(62,4),
(63,5),
(64,5),
(65,2),
(66,2),
(67,3),
(68,3),
(69,4),
(70,4),
(71,5),
(72,5),
(73,2),
(74,2),
(75,3),
(76,3),
(77,4),
(78,4),
(79,5),
(80,5),
(81,2),
(82,2),
(83,3),
(84,3),
(85,4),
(86,4),
(87,5),
(88,5),
(89,2),
(90,2),
(91,3),
(92,3),
(93,4),
(94,4),
(95,5),
(96,5),
(97,4),
(98,4),
(99,5),
(100,5)
GO

insert into [Data_Governance].app.UserLDAPGroups (AccountName, GroupName, GroupEmail, GroupType) VALUES
('Accident and Emergency Group','Accident and Emergency Group (Group)','Accident_and_Emergency@my_hospital.rocks','Email Distribution'),
('Admissions Group','Admissions Group (Group)','Admissions@my_hospital.rocks','Email Distribution'),
('Cardiology Group','Cardiology Group (Group)','Cardiology@my_hospital.rocks','Email Distribution'),
('Oncology Group','Oncology Group (Group)','Oncology@my_hospital.rocks','Email Distribution'),
('Pharmacy Group','Pharmacy Group (Group)','Pharmacy@my_hospital.rocks','Email Distribution'),
('Radiotherapy Group','Radiotherapy Group (Group)','Radiotherapy@my_hospital.rocks','Email Distribution'),
('Urology Group','Urology Group (Group)','Urology@my_hospital.rocks','Email Distribution'),
('Analytics Group','Analytics Group (Group)','Analytics@my_hospital.rocks','Email Distribution'),
('Ophthalmology Group','Ophthalmology Group (Group)','Ophthalmology@my_hospital.rocks','Email Distribution'),
('Orthopaedics Group','Orthopaedics Group (Group)','Orthopaedics@my_hospital.rocks','Email Distribution')
GO
insert into [Data_Governance].app.UserLDAPGroupMembership (UserId,GroupId) values 
(1,1),
(2,1),
(3,1),
(4,1),
(5,1),
(6,1),
(7,1),
(8,1),
(9,1),
(10,1),
(11,1),
(12,1),
(13,1),
(14,1),
(15,1),
(16,2),
(17,2),
(18,2),
(19,2),
(20,2),
(21,2),
(22,2),
(23,2),
(24,2),
(25,2),
(26,2),
(27,3),
(28,3),
(29,3),
(30,3),
(31,3),
(32,4),
(33,4),
(34,4),
(35,4),
(36,4),
(37,4),
(38,4),
(39,5),
(40,5),
(41,5),
(42,5),
(43,5),
(44,5),
(45,5),
(46,5),
(47,6),
(48,6),
(49,6),
(50,6),
(51,6),
(52,6),
(53,6),
(54,6),
(55,6),
(56,6),
(57,6),
(58,6),
(59,7),
(60,7),
(61,7),
(62,7),
(63,7),
(64,7),
(65,7),
(66,7),
(67,8),
(68,8),
(69,8),
(70,8),
(71,8),
(72,8),
(73,8),
(74,8),
(75,8),
(76,8),
(77,8),
(78,8),
(79,8),
(80,9),
(81,9),
(82,9),
(83,9),
(84,9),
(85,9),
(86,9),
(87,10),
(88,10),
(89,10),
(90,10),
(91,10),
(92,10),
(93,10),
(94,10),
(95,10),
(96,10),
(97,10),
(98,10),
(99,10),
(100,10)
GO

-- run packages to load search data
DECLARE @RC int
EXECUTE @RC = [Data_Governance].[app].[Search_MasterDataUpdate] 
GO

select 'completed';