/*
    Atlas of Information Management business intelligence library and documentation database.
    Copyright (C) 2020  Riverside Healthcare, Kankakee, IL

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

USE [master]
GO
/****** Object:  Database [LDAP]    Script Date: 3/18/2020 3:44:50 PM ******/
CREATE DATABASE [LDAP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LDAP', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\LDAP.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LDAP_log', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Data\LDAP_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [LDAP] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LDAP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LDAP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LDAP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LDAP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LDAP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LDAP] SET ARITHABORT OFF 
GO
ALTER DATABASE [LDAP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LDAP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LDAP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LDAP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LDAP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LDAP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LDAP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LDAP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LDAP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LDAP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LDAP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LDAP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LDAP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LDAP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LDAP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LDAP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LDAP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LDAP] SET RECOVERY FULL 
GO
ALTER DATABASE [LDAP] SET  MULTI_USER 
GO
ALTER DATABASE [LDAP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LDAP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LDAP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LDAP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LDAP] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LDAP] SET QUERY_STORE = OFF
GO
USE [LDAP]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [LDAP]
GO


ALTER ROLE [db_datareader] ADD MEMBER [datagov]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [datagov]
GO
/****** Object:  Table [dbo].[Groups]    Script Date: 3/18/2020 3:44:53 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Groups](
	[GroupId] [int] IDENTITY(1,1) NOT NULL,
	[AccountName] [nvarchar](max) NULL,
	[GroupName] [nvarchar](max) NULL,
	[GroupEmail] [nvarchar](max) NULL,
	[GroupType] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[GroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Memberships]    Script Date: 3/18/2020 3:44:54 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Memberships](
	[MembershipId] [int] IDENTITY(1,1) NOT NULL,
	[AccountName] [nvarchar](max) NULL,
	[GroupType] [nvarchar](max) NULL,
	[GroupName] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[MembershipId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 3/18/2020 3:44:54 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Base] [nvarchar](max) NULL,
	[EmployeeId] [nvarchar](max) NULL,
	[AccountName] [nvarchar](max) NULL,
	[DisplayName] [nvarchar](max) NULL,
	[FullName] [nvarchar](max) NULL,
	[FirstName] [nvarchar](max) NULL,
	[LastName] [nvarchar](max) NULL,
	[Department] [nvarchar](max) NULL,
	[Title] [nvarchar](max) NULL,
	[Phone] [nvarchar](max) NULL,
	[Email] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [LDAP] SET  READ_WRITE 
GO
