name: Release

on:
  push:
    branches-ignore:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

        with:
          fetch-depth: 0
          persist-credentials: false
      - name: setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093
        with:
          version: 10.34.5
      - name: setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: '24.x'
          cache: 'pnpm'
      - name: install node deps
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@1c8dbaa298552ad40802cf44320879943de90278
        with:
          semantic_version: 24
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: true
          NPM_CONFIG_AUDIT: false
          NPM_CONFIG_FUND: false
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
