name: Release

on:
  push:
    branches-ignore:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        with:
          fetch-depth: 0
          persist-credentials: false
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: install node deps
        run: npm install
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        with:
          semantic_version: 24
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: true
          NPM_CONFIG_AUDIT: false
          NPM_CONFIG_FUND: false
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
