name: Release

on:
  push:
    branches-ignore:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

        with:
          fetch-depth: 0
          persist-credentials: false
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
      - name: install node deps
        run: npm install --ignore-scripts --no-audit --no-fund
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@e0b75dd3b943e75f6bea693cc69caf82c26c0571
        with:
          semantic_version: 24
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: true
          NPM_CONFIG_AUDIT: false
          NPM_CONFIG_FUND: false
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
